name: Test Docker Local

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker: [
          fedora-32-amd64, # TODO:
        ]

    name: ${{ matrix.docker }}

    steps:
    - uses: actions/checkout@v2

    - name: Build system information
      run: python .github/workflows/system-info.py

    - name: Docker build
      run: |
        docker build . -t builder -f .github/workflows/images/${{ matrix.docker }}/Dockerfile

    - name: Docker build
      run: |
        # The Pillow user in the docker container is UID 1000
        sudo chown -R 1000 $GITHUB_WORKSPACE
        docker run --name pillow_container  -v $GITHUB_WORKSPACE:/Pillow builder
        sudo chown -R runner $GITHUB_WORKSPACE

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        flags: GHA_Docker
        name: ${{ matrix.docker }}